### ISSUE TITLE
Kurulum ve Kullanım Hk.

### ISSUE THREAD

**Issue by yasin-dogan38** [ismail0234/trendyol-php-api#10]
Merhaba,
Öncelikle böyle bir projeyi hazırladığınız için teşekkür ederiz.
Kurulumum ve kullanım kısmında destek olabilir misiniz? composer sonrası için bilgimiz yok
Teşekkürler.

**Comment by ismail0234** [comment]
Kullanım için README Dosyasına bakabilirsiniz bütün örnekler ve açıklamaları mevcut.
