### ISSUE TITLE
Create product V2

### ISSUE THREAD

**Issue by iozkn** [ismail0234/trendyol-php-api#11]
Üstadım selamlar. Projeni kullanarak bir süredir geliştirme yapıyorum. Paketin içerisinde ürün oluşturma bulunmadığı için kendim eklemek durumunda kaldım. Arzu ederseniz paylaşabilirim. Teşekkürler.

**Comment by garsamba** [comment]
> Üstadım selamlar. Projeni kullanarak bir süredir geliştirme yapıyorum. Paketin içerisinde ürün oluşturma bulunmadığı için kendim eklemek durumunda kaldım. Arzu ederseniz paylaşabilirim. Teşekkürler.

valla eklersen iyi olur hocam.

**Comment by ismail0234** [comment]
> Üstadım selamlar. Projeni kullanarak bir süredir geliştirme yapıyorum. Paketin içerisinde ürün oluşturma bulunmadığı için kendim eklemek durumunda kaldım. Arzu ederseniz paylaşabilirim. Teşekkürler.

Elbette, Pull Request olarak gönderirseniz inceledikten sonra ekleyebilirim.

**Comment by iozkn** [comment]
> > Üstadım selamlar. Projeni kullanarak bir süredir geliştirme yapıyorum. Paketin içerisinde ürün oluşturma bulunmadığı için kendim eklemek durumunda kaldım. Arzu ederseniz paylaşabilirim. Teşekkürler.
> 
> Elbette, Pull Request olarak gönderirseniz inceledikten sonra ekleyebilirim.

Eklendi. Kontrol edebilirsiniz.

**Comment by garsamba** [comment]
> Üstadım selamlar. Projeni kullanarak bir süredir geliştirme yapıyorum. Paketin içerisinde ürün oluşturma bulunmadığı için kendim eklemek durumunda kaldım. Arzu ederseniz paylaşabilirim. Teşekkürler.

artı olarak getClaims içinde çalışma bekliyoruz hocam :)

**Comment by iozkn** [comment]
> > Üstadım selamlar. Projeni kullanarak bir süredir geliştirme yapıyorum. Paketin içerisinde ürün oluşturma bulunmadığı için kendim eklemek durumunda kaldım. Arzu ederseniz paylaşabilirim. Teşekkürler.
> 
> artı olarak getClaims içinde çalışma bekliyoruz hocam :)

Henüz projem o seviyeye gelmedi. Benden önce eklenmezse elbette paylaşırım.
