### ISSUE TITLE
Geçersiz Servis!

### ISSUE THREAD

**Issue by garsamba** [ismail0234/trendyol-php-api#12]
merhaba,
herzaman çalışan sistem için 1 haftadır Geçersiz Servis! demeye başladı, sanırım trendyol api linki için diyor, sorun nedir acaba.

**Comment by ismail0234** [comment]
Yeni versiyonu deneyebilirsiniz sorun varsa düzelmiştir.

**Comment by garsamba** [comment]
> Yeni versiyonu deneyebilirsiniz sorun varsa düzelmiştir.

yeni indirdim şuan ancak arkadaşın pull requests olarak eklediği ürün yükleme görünmüyor, burada dosyalara baktığımda kodlar içinde var ama composer ile indirdiğimde eski dosyalar var.

**Comment by ismail0234** [comment]
Composer otomatik güncellenmemiş. Şuan manuel olarak güncelledim.
