### ISSUE TITLE
Tam Kurulum Bilgisi

### ISSUE THREAD

**Issue by baranselpamuk** [ismail0234/trendyol-php-api#15]
Merhaba, Kütüphanenizi İnceledim Hatta Çok Güzel Bir Çok Yerde Olmayan Şeyler Var.
Sorun Şurada Başlıyor ; API Key, Satıcı ID, API Secret Bilgilerini Tam Olarak Nereye Gireceğim? 
Bunları 2 Gündür Bir Türlü Bulamadım. Amacım Trendyol Siparişlerimi Çekmek Sadece. Diğer Bilgilere İhtiyacım Yok Ama Ürünleri Çekmem Lazım. Readme.md'de Anlatmışsınız Kurulum Ancak Composer kullanamadığım için yapamadım. bu konuda yardım edermisiniz? neyi nasıl yapıp ürünleri çekeceğim hakkında.

**Comment by alimsahy** [comment]
> Merhaba, Kütüphanenizi İnceledim Hatta Çok Güzel Bir Çok Yerde Olmayan Şeyler Var.
> Sorun Şurada Başlıyor ; API Key, Satıcı ID, API Secret Bilgilerini Tam Olarak Nereye Gireceğim?
> Bunları 2 Gündür Bir Türlü Bulamadım. Amacım Trendyol Siparişlerimi Çekmek Sadece. Diğer Bilgilere İhtiyacım Yok Ama Ürünleri Çekmem Lazım. Readme.md'de Anlatmışsınız Kurulum Ancak Composer kullanamadığım için yapamadım. bu konuda yardım edermisiniz? neyi nasıl yapıp ürünleri çekeceğim hakkında.

Merhaba,

Composer olmadan oncelikle manuel olarak dosyalari indirin. namespace ozelligi veya include ile calistiginiz dosyaya TrendyolClient.php dosyasini cagirin.

```php
use IS\PazarYeri\Trendyol\TrendyolClient;
//veya
include 'TrendyolClient.php';
```
Daha sonra [README.MD](../README.MD) verilen ornekteki gibi api bilgilerinizi girip kullanmaya baslayabilirsiniz.
```php
$trendyol = new TrendyolClient(); 
$trendyol->setSupplierId(100000);
$trendyol->setUsername("xxxxxxxxxxxxxxxxxxxx");
$trendyol->setPassword("xxxxxxxxxxxxxxxxxxxx");
```

**Comment by ismail0234** [comment]
> > Merhaba, Kütüphanenizi İnceledim Hatta Çok Güzel Bir Çok Yerde Olmayan Şeyler Var.
> > Sorun Şurada Başlıyor ; API Key, Satıcı ID, API Secret Bilgilerini Tam Olarak Nereye Gireceğim?
> > Bunları 2 Gündür Bir Türlü Bulamadım. Amacım Trendyol Siparişlerimi Çekmek Sadece. Diğer Bilgilere İhtiyacım Yok Ama Ürünleri Çekmem Lazım. Readme.md'de Anlatmışsınız Kurulum Ancak Composer kullanamadığım için yapamadım. bu konuda yardım edermisiniz? neyi nasıl yapıp ürünleri çekeceğim hakkında.
> 
> Merhaba,
> 
> Composer olmadan oncelikle manuel olarak dosyalari indirin. namespace ozelligi veya include ile calistiginiz dosyaya TrendyolClient.php dosyasini cagirin.
> 
> ```
> use IS\PazarYeri\Trendyol\TrendyolClient;
> //veya
> include 'TrendyolClient.php';
> ```
> 
> Daha sonra [README.MD](../README.MD) verilen ornekteki gibi api bilgilerinizi girip kullanmaya baslayabilirsiniz.
> 
> ```
> $trendyol = new TrendyolClient(); 
> $trendyol->setSupplierId(100000);
> $trendyol->setUsername("xxxxxxxxxxxxxxxxxxxx");
> $trendyol->setPassword("xxxxxxxxxxxxxxxxxxxx");
> ```

Manuel olarak indirmeyi şahsen tavsiye etmiyorum. Sağlıklı bir kurulum için composer kullanmanızı tavsiye ederim.
