### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by simirfan** [ismail0234/trendyol-php-api#2]
![image](https://user-images.githubusercontent.com/6439279/83017256-fef92480-a02b-11ea-815c-93623986d1df.png)

![image](https://user-images.githubusercontent.com/6439279/83017303-16381200-a02c-11ea-971d-0e3e1551cb62.png)

buraya bir static eklemek gerek

Helper > Format.php 50.satır

**Comment by ismail0234** [comment]
@simirfan geri bildirimin ve katkın için teşekkürler. Bu nasıl gözden kaçmış anlam veremedim. v1.0.6 versiyonu ile sorun düzeltilmiştir.
