### ISSUE TITLE
Ürün bilgilerini güncelleme

### ISSUE THREAD

**Issue by hasanuzn** [ismail0234/trendyol-php-api#20]
Merhaba, paket genel olarak çok iyi bunun için çok teşekkür ederim fakat ürün detayı güncellemeye ihtiyacım vardı ve eksikti şu şekilde bir düzenleme yaptım.

"_IS/Pazaryeri/Trendyol/Services/ProductService.php_" içerisine aşağıda bulunan fonksiyonu ekleyin.

    /**
     * Ürün bilgilerini güncellemek için kullanılır. (Fiyat ve stok güncellemek için updatePriceAndInventory fonksiyonu kullanılmalıdır)
     *
     *
     * @param array $data
     * @return array
     * @throws TrendyolException
     */
    public function updateProducts($data = array())
    {
        $this->setApiUrl('https://api.trendyol.com/sapigw/suppliers/{supplierId}/v2/products');
        $this->setMethod("PUT");
        $query = array(
            'items'=> array( 
                'barcode'               => '',
                'title'                 => '',
                'productMainId'         => '',
                'brandId'               => '',
                'categoryId'            => '',
                'quantity'              => '',
                'stockCode'             => '',
                'dimensionalWeight'     => '',
                'description'           => '',
                'currencyType'          => '',
                'listPrice'             => '',
                'salePrice'             => '',
                'cargoCompanyId'        => '',
                'deliveryDuration'      => '',
                'images'                => '',
                'vatRate'               => '',
                'shipmentAddressId'     => '',
                'returningAddressId'    => '',
                'attributes'            => ''
            ),
        );

        return $this->getResponse($query, $data);
    }

 
Daha sonra "_IS/Pazaryeri/Trendyol/Helper/Request.php_" içerisinden `$this->method == 'POST'` aramasını yaparak `$this->method == 'POST' || $this->method == 'PUT'` olarak değiştirin.

**Comment by ismail0234** [comment]
Merhaba,

Yaptığın düzenlemeleri commit atabilir misin?

**Comment by ismail0234** [comment]
Katkı için teşekkürler
