### ISSUE TITLE
Trendyol boş yanıt döndürdü

### ISSUE THREAD

**Issue by Hasokeyk** [ismail0234/trendyol-php-api#22]
Merhabalar,

Kütüphaneye bilgileri girdiğim zaman 

```sh
Fatal error: Uncaught IS\PazarYeri\Trendyol\Helper\TrendyolException: Trendyol boş yanıt döndürdü. in C:\wamp64\www\test\trendyol-test\vendor\ismail0234\trendyol-php-api\IS\PazarYeri\Trendyol\Helper\Request.php on line 259
```

Hatası alıyorum.

**Comment by ismail0234** [comment]
Merhaba,

Trendyol tarafından cevap alınamadığı zaman bu hata mesajı alınmaktadır. Anlık bir sorun olabilir ya da trendyol sizi engellemiş olabilir. Trendyolun sizi engelleyip/engellemediğini kontrol edebilir misiniz?

**Comment by Hasokeyk** [comment]
Localhosttan bağlandığım için sonuç göndermiyormuş sunucuya atınca sorunsuz bağlandı teşekkür ederim. :)

**Comment by ismail0234** [comment]
Sorunun çözülmesine sevindim 🙏
