### ISSUE TITLE
Fatal error Format::unixFormat()

### ISSUE THREAD

**Issue by garsamba** [ismail0234/trendyol-php-api#4]
merhaba ürün listelemeyi kullanmak istediğimde aşağıdaki hatayı oluyorum, diğer listelemelerde bir sorun yok..

Fatal error: Call to undefined method IS\PazarYeri\Trendyol\Helper\Format::unixFormat() in vendor\ismail0234\trendyol-php-api\IS\PazarYeri\Trendyol\Helper\Format.php on line 39

**Comment by ismail0234** [comment]
v1.0.7 sürümünde sorun düzeltildi. Bildirimin için teşekkürler
