### ISSUE TITLE
amazon için ?

### ISSUE THREAD

**Issue by esakarya** [ismail0234/trendyol-php-api#5]
eline sağlık güzel paylaşımlar.. amazon için bu tarz bi paylaşım yapmayı düşünüyormusun ?
ve yurtici kargo için ?

**Comment by ismail0234** [comment]
amazon veya yurtiçi ile alakalı hiç proje geliştirmediğim için şuanlık düşünmüyorum.

**Comment by esakarya** [comment]
teşekkür ettim
