### ISSUE TITLE
Api çalışmıyor

### ISSUE THREAD

**Issue by garsamba** [ismail0234/trendyol-php-api#9]
api malesef çalışmamaya başladı ismail hocam.

**Comment by ismail0234** [comment]
Aldığınız hata nedir ?

**Comment by garsamba** [comment]
şuan kontrol ettiğimde sanırım ürün ekleme ve ürün çekme filtreleme işlemi çalışmıyor, sipariş çekme çalışıyor,
boş veri geliyor ismail hocam aylardır kullanıyordum oysaki

stdClass Object ( [timestamp] => 1616362328517 [exception] => TrendyolSystemException [errors] => Array ( [0] => stdClass Object ( [key] => generic.exception [message] => Exception Occured [errorCode] => ) ) )

**Comment by garsamba** [comment]
> Aldığınız hata nedir ?

şuan kontrol ettiğimde sanırım ürün ekleme ve ürün çekme filtreleme işlemi çalışmıyor, sipariş çekme çalışıyor,
boş veri geliyor ismail hocam aylardır kullanıyordum oysaki

stdClass Object ( [timestamp] => 1616362328517 [exception] => TrendyolSystemException [errors] => Array ( [0] => stdClass Object ( [key] => generic.exception [message] => Exception Occured [errorCode] => ) ) )

**Comment by ismail0234** [comment]
En son sürüme güncelleyip kullandınızmı?

**Comment by garsamba** [comment]
güncelledim hocam zaten 4-5 gündür çalışmıyor, sadece ürün yükleme ve ürünleri çekme çalışmıyor, siparişleri iadeler hepsini çekiyor tek çalışmayan Product Service olayı.

**Comment by ismail0234** [comment]
Bir aksilik çıkmaz ise bunu bu hafta kontrol edeceğim.
